"""First commit

Revision ID: 26dd889ef799
Revises: 864bdc030ff3
Create Date: 2022-07-15 17:23:10.806373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dd889ef799'
down_revision = '864bdc030ff3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handlers', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handlers', 'version')
    # ### end Alembic commands ###
