kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: triton-external
spec:
  hosts:
    - '*'
  gateways:
    - {{ .Values.gatewayNamespace }}/{{ .Values.gatewayName }}
  http:
    - match:
        - uri:
            prefix: / # catch all rule
      route:
        - destination:
            host: triton-inference-server-service
            port:
              number: 8000
    #   rewrite:
    #     uri: /
