apiVersion: v1
kind: Service
metadata:
  name: {{ handler_name }}-service
  namespace: {{ namespace }}
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: {{ handler_name }}
  clusterIP: None