# We want to make the control plane accessible from outside the cluster
# so that we can test it with the Python client
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ endpoint_name }}
spec:
  hosts: 
  - "*"
  gateways: 
  - {{ gateway_namespace}}/{{ gateway_name }}
  http:
  - match:
    - uri:
        prefix: "/{{ endpoint_name }}/"
    - uri:
        prefix: "/{{ endpoint_name }}"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: {{ endpoint_name }}
          port:
            number: 80
