apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlplane
spec:
  selector:
    matchLabels:
      app: controlplane
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: controlplane
    spec:
      serviceAccountName: flighty-control-plane
      initContainers:
        - name: "wait-for-alembic"
          image: "ghcr.io/groundnuty/k8s-wait-for:v1.6"
          imagePullPolicy: Always
          args:
            - "job"
            - "db-upgrade"
      containers:
        - image: docker.io/gvashishtha/flighty:controlplane
          name: controlplane
          env:
          - name: FAST_API_ROOT
            value: "/api/v1"
          - name: DB_URL
            value: mysql.{{ .Release.Namespace }}.svc.cluster.local
          - name: GATEWAY_NAME
            value: {{ .Values.gatewayName }}
          - name: GATEWAY_NAMESPACE
            value: {{ .Values.gatewayNamespace }}
          - name: K8S_NAMESPACE
            value: {{ .Release.Namespace }}
          ports:
            - containerPort: 80
              name: controlplane
          volumeMounts:
            - name: model-store
              mountPath: /code/flighty-files
          imagePullPolicy: Always
      volumes:
        - name: model-store
          persistentVolumeClaim:
            claimName: model-store-pvc
      imagePullSecrets:
        - name: regcred
