apiVersion: batch/v1
kind: Job
metadata:
  name: db-upgrade
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        job: db-upgrade
    spec:
      serviceAccountName: flighty-control-plane
      restartPolicy: OnFailure
      initContainers:
        - name: "wait-for-mysql"
          image: "ghcr.io/groundnuty/k8s-wait-for:v1.6"
          imagePullPolicy: Always
          args:
            - "service"
            - "mysql"
      containers:
        - name: alembic
          image: docker.io/gvashishtha/flighty:alembic
          #args: ["downgrade", "-1"]
          args: ["upgrade", "864bdc030ff3"]
      imagePullSecrets:
        - name: regcred