apiVersion: batch/v1
kind: Job
metadata:
  name: db-upgrade
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        job: db-upgrade
      annotations:
        values.global.proxy.holdApplicationUntilProxyStarts: "true"
    spec:
      serviceAccountName: flighty-control-plane
      restartPolicy: OnFailure
      initContainers:
        - name: "wait-for-mysql"
          image: "ghcr.io/groundnuty/k8s-wait-for:v1.6"
          args:
            - service
            - mysql
      containers:
        - name: alembic
          imagePullPolicy: Always
          image: docker.io/gvashishtha/flighty:alembic
          env:
          - name: DB_URL
            value: mysql.{{ .Release.Namespace }}.svc.cluster.local
          command:
            # once alembic succeeds, kill envoy-proxy manually so we can exit, see
            # https://stackoverflow.com/questions/54921054/ for more info
            - /bin/sh
            - -c
            - |
              alembic {{ .Values.alembicCommand }}
              x=$(echo $?); 
              if [ $x -eq 0 ]; then
                curl -fsI -X POST http://localhost:15020/quitquitquit
              fi
              exit $x
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: regcred