apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  #volumeName: pv-mysql