apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-store-pvc
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi