kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flighty-control-plane
subjects:
  - kind: ServiceAccount
    name: flighty-control-plane
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: flighty-control-plane
  apiGroup: rbac.authorization.k8s.io