kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flighty-control-plane
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: [ "deployments", "services"]
    verbs: ["get", "create", "watch", "list", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "list", "delete"]