kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flighty-control-plane
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "create", "watch", "list", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: [ "deployments"]
    verbs: ["get", "create", "watch", "list", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "list", "delete"]
  - apiGroups: ["networking.istio.io"]
    resources: ["destinationrules", "virtualservices"]
    verbs: ["get", "create", "watch", "list", "update", "patch", "delete"]