apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
spec:
  containers:
    - image: docker.io/gvashishtha/flighty:model_server
      name: test
      imagePullPolicy: IfNotPresent
      volumeMounts:
            - name: model-store
              mountPath: /code/flighty-files/first-artifact/2
              subPath: first-artifact/2
  imagePullSecrets:
    - name: regcred
  restartPolicy: Always
  volumes:
    - name: model-store
      persistentVolumeClaim:
        claimName: model-store-pvc
status: {}
